<!DOCTYPE html>
<html>
    <head>
        <!--/ALL META TAGS/-->
        <meta charset="UTF-8">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
        <!--/END OF META TAG/-->
        <title>Certificate</title>
        <style type="text/css">
        /* This stylesheet generated by Transfonter (http://transfonter.org) on September 2, 2016 10:44 AM */


        .clear{margin: 0;padding: 0;clear: both;width: 100%;}
        .certificate-wrapper{width: 1346px;height: 830px;margin: 0 auto;background: url('{certificate_path}/main_bg.png') no-repeat scroll 0 0 #feffff;/*background: red;*/}
        .certificate_left{height: 100%;width: 359px;background: url('{certificate_path}/certificate_left.png') no-repeat scroll 0 0 transparent;display: table;float: left;}
        .certificate_left_inner {display: table-cell;vertical-align: bottom;}
        .certificate_right{width: 987px;float: left;}
        .certificate_main_title{border-bottom: 1px solid #1980b2;color: #010101;font-family: "Vladimir Script";font-size: 80px;margin-left: 69px;padding-bottom: 16px;padding-top: 62px;}

        .certificate_right, .certificate_inner_right, .certificate_inner_left{height: 830px;}
        .certificate_inner_right{background: url('{certificate_path}/main_bg_right.png') no-repeat scroll right top transparent;}
        .certificate_inner_left{background: url('{certificate_path}/main_bg_left.png') no-repeat scroll left bottom transparent;}
        .certificate_middle_content{margin-left: 69px;padding-top: 107px;}
        .blue_title{color: #1980b2;font-size: 20px;font-family: 'Ebrima';}
        .user_name_printable {border-bottom: 1px solid #1980b2;color: #000000;display: inline-block;font-family: "Roboto";font-size: 62px;font-weight: 300;margin-bottom: 9px;padding: 2px 0;}
        .fundamental_titles{color: #000000;font-family: "Vladimir Script";font-size: 50px;margin-top: 20px;}

        .certificate_footer {display: table;width: 100%;margin-top: 113px;}
        .certificate_widget_left {display: table-cell;vertical-align: middle;}
        .certificate_widget_middle {display: table-cell;margin: 0 auto;vertical-align: middle;}
        .certificate_widget_right {display: table-cell;vertical-align: middle; }

        .certificate_widget_left .certificate_widget_item, .certificate_widget_right .certificate_widget_item{display: inline-block;}
        .certificate_widget_left .certificate_widget_item{padding-left: 69px;}
        .certificate_widget_right .certificate_widget_item{padding-right: 49px;}
        .certificate_widget_right{text-align: right;}
        .certificate_widget_middle .stamp {text-align: center;}
        .certificate_widget_left .nameperson, .certificate_widget_right .nameperson{font-size: 30px;color: #020202;font-family: 'Silent Reaction';text-align: center;border-bottom: 1px solid #1a80b2; margin-bottom: 6px;}
        .certificate_widget_left .nameperson2, .certificate_widget_right .nameperson2{font-size: 20px;color: #1980b2;font-family: 'Ebrima';text-align: center;}
        .certificate_widget_left .nameperson_post, .certificate_widget_right .nameperson_post{font-size: 20px;color: #010101;font-family: 'Ebrima';text-align: center;font-style: italic;}
        </style>

    </head>
    <body>
        <div class="certificate-wrapper" style=' background: #feffff url("{certificate_path}/main_bg.png") no-repeat scroll 0 0;height: 830px;margin: 0 auto;width: 1346px;' >
            <div class="certificate_left">
                <div class="certificate_left_inner">
                    <img src="{certificate_path}/logo.png" alt="">
                </div>
                <div class="clear"></div>
            </div>
            <div class="certificate_right">
                <div class="certificate_inner_right">
                    <div class="certificate_inner_left">
                        <div class="certificate_main_title">Certificate of Achievement</div>
                        <div class="certificate_middle_content">
                            <div class="blue_title">This is to Certify that</div>
                            <div class="user_name_printable" id="print_user_name">{full_name}</div>
                            <div class="blue_title">successfully completed</div>
                            <div class="fundamental_titles">Fundamentals of Financial Awareness</div>
                        </div>
                        <div class="certificate_footer">
                            <div class="certificate_widget_left">
                               <div class="certificate_widget_item">
                                    <div class="nameperson">KevCochrn.</div>
                                    <div class="nameperson2">Kevin Cochran</div>
                                    <div class="nameperson_post">President</div>
                               </div>
                            </div>
                            <div class="certificate_widget_middle">
                                <div class="stamp"><img src="{certificate_path}/stamp.png" alt=""></div>
                            </div>
                            <div class="certificate_widget_right">
                                <div class="certificate_widget_item">
                                    <div class="nameperson">TPeterson</div>
                                    <div class="nameperson2">Todd Peterson</div>
                                    <div class="nameperson_post">Chief Executive Officer</div>
                                </div>
                            </div>
                        </div>

                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <div id="editor"></div>

    
    </body>


</html>
